FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
RUN apt-get install -y -qq npm

RUN ln -s /usr/bin/nodejs /usr/bin/node

# install bower

RUN npm install --global bower

# Build runtime imagecd\
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "bprapp.dll"]